apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: nginx
          image: 6065meet/static-portfolio:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-site-service
  namespace: portfolio
spec:
  selector:
    app: static-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

